### ISSUE TITLE
Smooth without break leaflet and another plugins

### ISSUE THREAD

**Issue by NaturelLaurent** [mutsuyuki/Leaflet.SmoothWheelZoom#2]
Hello,

How can we use your plugin without break leaflet and another plugins?

if you L.CircleMarker it's doesn't work anymore
why ?

if you don't use L.CircleMarker you can use this solution but it's hard coding but it's not very good solution in jquery
> if ($('#map:hover').length) {
>   $('html').css({overflow: 'hidden'});
>} else {
>    $('html').css({overflow: 'auto'});
>}

and add in your function _onWheelStart
map.scrollWheelZoom.disable(); // it's no break leaflet function scrollWheelZoom

can you help to me for fix it without change the overflow css in html and fix other marker like L.CircleMarker?

**Comment by mutsuyuki** [comment]
Thanks for the report.
I think that I fixed.
Please check new demo page.
[https://mutsuyuki.github.io/Leaflet.SmoothWheelZoom/](https://mutsuyuki.github.io/Leaflet.SmoothWheelZoom/)

**Comment by NaturelLaurent** [comment]
Hello, 

Thanks for your fix of circlemarker, it's work now but not the break of code leaflet.

If i use your code like that, it's doesn't work if I use  another plugins (like [https://github.com/CliffCloud/Leaflet.Sleep](https://github.com/CliffCloud/Leaflet.Sleep)) because you propose to remove the function scrollWheelZoom  (scrollWheelZoom: false, // disable original zoom function)

Can you fix it please ?
